const express = require("express");
const router = express.Router();
const protect = require("../middlewares/auth.middleware");
const authorize = require("../middlewares/role.middleware");
const c = require("../controllers/contracts/contract.controller");
router.get("/", protect, c.getAll);
router.get("/:id", protect, c.getOne);
router.post("/", protect, authorize("admin"), c.create);
router.put("/:id", protect, authorize("admin"), c.update);
router.delete("/:id", protect, authorize("admin"), c.remove);
module.exports = router;
