const InterimPayment = require("../models/InterimPayment");
const Contract = require("../models/Contract");
const generateBillNo = require("../utils/generateBillNo");
const {
   notifyInterimPaymentSubmitted,
   notifyInterimPaymentApproved,
   notifyPaymentRecorded,
} = require("./notification.service");

const num = (v) => Number(v || 0);

exports.createPayment = async (data, userId) => {
   const gross = num(data.currentGrossAmount ?? data.grossAmount);

   if (gross < 0) throw new Error("Gross amount cannot be negative");

   // duplicate bill number is impossible by construction (autogenerated),
   // but double check uniqueness
   const paymentNo = await generateBillNo();

   const existing = await InterimPayment.find();

   if (existing.some((b) => b.paymentNo === paymentNo)) {
      throw new Error("Duplicate bill number generated");
   }

   // contract value cap
   if (data.contract) {
      const contract = await Contract.findById(data.contract);

      if (contract) {
         const prior = (await InterimPayment.find())
            .filter(
               (b) =>
                  String(b.contract) === String(data.contract) &&
                  b.status !== "rejected",
            )
            .reduce((s, b) => s + num(b.currentGrossAmount ?? b.grossAmount), 0);

         const revisedValue =
            num(contract.value) + num(contract.approvedVariations);

         if (prior + gross > revisedValue) {
            throw new Error(
               `Billing exceeds contract value (${revisedValue}). Already billed: ${prior}`,
            );
         }
      }
   }

   const advanceRecovery = num(data.advanceRecovery);
   const retention = num(data.retention);
   const tax = num(data.tax);
   const otherDeductions = num(data.otherDeductions);

   const netAmount = Math.max(
      0,
      gross - advanceRecovery - retention - tax - otherDeductions,
   );

   return await InterimPayment.create({
      ...data,
      paymentNo,
      currentGrossAmount: gross,
      grossAmount: gross,
      netAmount,
      outstandingAmount: netAmount,
      approvedAmount: 0,
      paidAmount: 0,
      submissionDate: data.submissionDate || new Date().toISOString(),
      submittedBy: userId,
      status: "draft",
   });
};

const transitions = {
   draft: ["submitted"],
   submitted: ["under_review", "rejected"],
   under_review: ["approved", "rejected"],
   approved: ["partially_paid", "paid"],
   partially_paid: ["paid"],
   paid: [],
   rejected: [],
};

exports.transitionStatus = async (id, status, user) => {
   const bill = await InterimPayment.findById(id);

   if (!bill) throw new Error("Bill not found");

   if (!(transitions[bill.status] || []).includes(status)) {
      throw new Error(`Cannot move from ${bill.status} to ${status}`);
   }

   // role-based transition control
   const role = user.role;

   if (role === "site_supervisor" && status !== "submitted") {
      throw new Error("Site staff can only submit bills");
   }

   if (
      role === "accountant" &&
      !["under_review", "approved", "rejected"].includes(status)
   ) {
      throw new Error("Accountant can review/reject but not submit or approve-pay");
   }

   if (role !== "admin" && status === "paid") {
      throw new Error("Only admin can mark as fully paid");
   }

   bill.status = status;

   if (status === "approved") {
      bill.approvedAmount = num(bill.netAmount);
      bill.approvedBy = user._id;
      bill.approvalDate = new Date().toISOString();
      bill.outstandingAmount = Math.max(
         0,
         num(bill.approvedAmount) - num(bill.paidAmount),
      );
   }

   if (status === "submitted" || status === "under_review") {
      bill.submittedBy = user._id;
   }

   await bill.save();

   if (status === "submitted") {
      const populated = await InterimPayment.findById(bill._id)
         .populate("project", "name");
      await notifyInterimPaymentSubmitted(populated, user._id).catch(() => {});
   }

   if (status === "approved") {
      const populated = await InterimPayment.findById(bill._id)
         .populate("project", "name");
      await notifyInterimPaymentApproved(populated, user._id).catch(() => {});
   }

   return bill;
};

exports.recordPayment = async (id, amount, userId) => {
   const bill = await InterimPayment.findById(id);

   if (!bill) throw new Error("Bill not found");

   if (!["approved", "partially_paid"].includes(bill.status)) {
      throw new Error("Bill must be approved before payment");
   }

   amount = num(amount);

   if (amount <= 0) throw new Error("Payment amount must be positive");

   const base = num(bill.approvedAmount) || num(bill.netAmount);

   if (num(bill.paidAmount) + amount > base) {
      throw new Error("Payment exceeds approved amount");
   }

   bill.paidAmount = num(bill.paidAmount) + amount;

   bill.payments = [
      ...(bill.payments || []),
      { amount, date: new Date().toISOString(), by: userId },
   ];

   bill.outstandingAmount = Math.max(0, base - bill.paidAmount);

   bill.status = bill.outstandingAmount === 0 ? "paid" : "partially_paid";

   if (bill.status === "paid") bill.paymentDate = new Date().toISOString();

   await bill.save();

   const populated = await InterimPayment.findById(bill._id)
      .populate("project", "name");

   await notifyPaymentRecorded(populated, amount, userId).catch(() => {});

   return bill;
};

exports.getProjectFinancialSummary = async (projectId) => {
   const bills = (await InterimPayment.find()).filter(
      (b) => String(b.project?._id || b.project) === String(projectId),
   );

   const billed = bills
      .filter((b) => b.status !== "rejected" && b.status !== "draft")
      .reduce((s, b) => s + num(b.currentGrossAmount ?? b.grossAmount), 0);

   const approved = bills
      .filter((b) => ["approved", "partially_paid", "paid"].includes(b.status))
      .reduce((s, b) => s + num(b.approvedAmount), 0);

   const paid = bills.reduce((s, b) => s + num(b.paidAmount), 0);

   const outstanding = bills
      .filter((b) => ["approved", "partially_paid", "paid"].includes(b.status))
      .reduce((s, b) => s + num(b.outstandingAmount), 0);

   // contract remaining value
   const Contract = require("../models/Contract");

   const contracts = (await Contract.find()).filter(
      (c) => String(c.project) === String(projectId),
   );

   const contractValue = contracts.reduce(
      (s, c) => s + num(c.value) + num(c.approvedVariations),
      0,
   );

   return {
      contractValue,
      billed,
      approved,
      paid,
      outstanding,
      contractRemaining: contractValue - billed,
      cumulativeBilled: billed,
      cumulativeApproved: approved,
      cumulativePaid: paid,
   };
};
